### ISSUE TITLE
the webview can not get focused on using nestedwebview

### ISSUE THREAD

**Issue by itemon** [takahirom/webview-in-coordinatorlayout#1]
pls fix

**Comment by blinkmacalahan** [comment]
I'm not sure if this will solve your issue, but I noticed using this that the softkeyboard would not pop up when an HTML text input was selected. The input would get focus and you could see a cursor, but the keyboard never popped up.

I fixed this issue by passing in android.R.attr.webViewStyle as the 3rd parameter in the "this" call in the constructor with 2 parameters. See the code below:

```
public NestedWebView(Context context, AttributeSet attrs) {
    this(context, attrs, android.R.attr.webViewStyle);
}
```

**Comment by takahirom** [comment]
Thanks!!!
I could not solve this issue!
